mod ast;
mod parser;

use std::env;
use std::fs;

fn main() {
    let args: Vec<String> = env::args().collect();

    match args.get(1).map(|s| s.as_str()) {
        Some("--gen-phase1") => gen_phase1_output(),
        Some(path) => parse_file(path),
        None => run_demos(),
    }
}

fn parse_file(path: &str) {
    let input = fs::read_to_string(path).unwrap_or_else(|e| {
        eprintln!("Error reading {}: {}", path, e);
        std::process::exit(1);
    });
    match parser::parse(&input) {
        Ok(graph) => println!("{:#?}", graph),
        Err(e) => {
            eprintln!("Parse error:\n{}", e);
            std::process::exit(1);
        }
    }
}

fn run_demos() {
    let examples: &[(&str, &str)] = &[
        ("simple_chain", "[A] --> [B] --> [C]\n"),
        ("direction_lr", "direction: LR\n[Start] --> [End]\n"),
        ("node_shapes", "[Rect]\n(Rounded)\n{Diamond}\n((Circle))\n"),
        ("edge_types", "[A] --> [B]\n[A] -- [C]\n[A] ==> [D]\n[A] .--> [E]\n"),
        ("with_attrs", "[Node A] --> [Node B] { label: \"depends on\" }\n"),
        ("subgraph", "subgraph \"Group\" {\n  [A] --> [B]\n}\n"),
        ("bidirectional", "[X] <--> [Y]\n"),
        ("back_arrow", "[B] <-- [A]\n"),
    ];

    for (name, src) in examples {
        println!("=== Example: {} ===", name);
        println!("Input:\n{}", src.trim());
        println!("---");
        match parser::parse(src) {
            Ok(graph) => println!("{:#?}", graph),
            Err(e) => println!("PARSE ERROR:\n{}", e),
        }
        println!();
    }
}

/// Generate out/phase1/ output files from phase0 syntax examples.
fn gen_phase1_output() {
    fs::create_dir_all("out/phase1").unwrap();

    let examples_txt = fs::read_to_string("out/phase0/syntax_examples.txt")
        .expect("Cannot read out/phase0/syntax_examples.txt");

    // Parse each EXAMPLE N block from the file.
    let examples = extract_examples(&examples_txt);

    let mut ast_out = String::new();
    let mut err_out = String::new();

    // Also test intentionally malformed inputs for parse_errors.txt
    let bad_inputs: &[(&str, &str)] = &[
        ("missing_closing_bracket", "[A --> [B]\n"),
        ("empty_edge_target", "[A] -->\n"),
        ("bad_direction", "direction: DIAG\n[A] --> [B]\n"),
        ("unclosed_subgraph", "subgraph \"Foo\" {\n  [A]\n"),
        ("unknown_token", "@ invalid @\n"),
    ];

    ast_out.push_str("# Phase 1: AST Dump\n");
    ast_out.push_str("# Generated by: cargo run -- --gen-phase1\n");
    ast_out.push_str("# Each example parsed from out/phase0/syntax_examples.txt\n\n");

    err_out.push_str("# Phase 1: Parse Error Examples\n");
    err_out.push_str("# Generated by: cargo run -- --gen-phase1\n\n");

    for (title, src) in &examples {
        ast_out.push_str(&format!("{}\n", "=".repeat(80)));
        ast_out.push_str(&format!("{}\n", title));
        ast_out.push_str(&format!("{}\n", "=".repeat(80)));
        ast_out.push_str("\nInput:\n");
        ast_out.push_str(src.trim());
        ast_out.push_str("\n\nParsed AST:\n");
        match parser::parse(src) {
            Ok(graph) => {
                ast_out.push_str(&format!("{:#?}", graph));
            }
            Err(e) => {
                ast_out.push_str(&format!("PARSE ERROR:\n{}", e));
            }
        }
        ast_out.push_str("\n\n");
    }

    for (label, src) in bad_inputs {
        err_out.push_str(&format!("{}\n", "=".repeat(80)));
        err_out.push_str(&format!("Bad input: {}\n", label));
        err_out.push_str(&format!("{}\n", "=".repeat(80)));
        err_out.push_str("\nInput:\n");
        err_out.push_str(src.trim());
        err_out.push_str("\n\nError:\n");
        match parser::parse(src) {
            Ok(graph) => {
                err_out.push_str(&format!("(parsed successfully — expected error)\n{:#?}", graph));
            }
            Err(e) => {
                err_out.push_str(&e);
            }
        }
        err_out.push_str("\n\n");
    }

    let ast_path = "out/phase1/ast_dump.txt";
    let err_path = "out/phase1/parse_errors.txt";

    fs::write(ast_path, &ast_out).expect("Cannot write ast_dump.txt");
    fs::write(err_path, &err_out).expect("Cannot write parse_errors.txt");

    println!("Generated {}", ast_path);
    println!("Generated {}", err_path);
}

/// Extract (title, body) pairs from the syntax_examples.txt format.
fn extract_examples(text: &str) -> Vec<(String, String)> {
    let mut results = Vec::new();
    let separator = "=".repeat(80);
    let mut lines = text.lines().peekable();
    let mut current_title: Option<String> = None;
    let mut current_body = String::new();
    let mut in_body = false;

    while let Some(line) = lines.next() {
        if line == separator {
            // Next line is the title, then another separator
            if let Some(title_line) = lines.next() {
                let _sep2 = lines.next(); // consume closing separator
                // Save previous example if any
                if let Some(title) = current_title.take() {
                    let trimmed = current_body.trim().to_string();
                    if !trimmed.is_empty() {
                        results.push((title, format!("{}\n", trimmed)));
                    }
                }
                current_title = Some(title_line.trim().to_string());
                current_body.clear();
                in_body = true;
            }
        } else if in_body {
            current_body.push_str(line);
            current_body.push('\n');
        }
    }

    // Push last example
    if let Some(title) = current_title {
        let trimmed = current_body.trim().to_string();
        if !trimmed.is_empty() {
            results.push((title, format!("{}\n", trimmed)));
        }
    }

    results
}
