mod ast;
mod graph;
mod layout;
mod parser;

use std::env;
use std::fs;

fn main() {
    let args: Vec<String> = env::args().collect();

    match args.get(1).map(|s| s.as_str()) {
        Some("--gen-phase1") => gen_phase1_output(),
        Some("--gen-phase2") => gen_phase2_output(),
        Some("--gen-phase3") => gen_phase3_output(),
        Some(path) => parse_file(path),
        None => run_demos(),
    }
}

fn parse_file(path: &str) {
    let input = fs::read_to_string(path).unwrap_or_else(|e| {
        eprintln!("Error reading {}: {}", path, e);
        std::process::exit(1);
    });
    match parser::parse(&input) {
        Ok(graph) => println!("{:#?}", graph),
        Err(e) => {
            eprintln!("Parse error:\n{}", e);
            std::process::exit(1);
        }
    }
}

fn run_demos() {
    let examples: &[(&str, &str)] = &[
        ("simple_chain", "[A] --> [B] --> [C]\n"),
        ("direction_lr", "direction: LR\n[Start] --> [End]\n"),
        ("node_shapes", "[Rect]\n(Rounded)\n{Diamond}\n((Circle))\n"),
        ("edge_types", "[A] --> [B]\n[A] -- [C]\n[A] ==> [D]\n[A] .--> [E]\n"),
        ("with_attrs", "[Node A] --> [Node B] { label: \"depends on\" }\n"),
        ("subgraph", "subgraph \"Group\" {\n  [A] --> [B]\n}\n"),
        ("bidirectional", "[X] <--> [Y]\n"),
        ("back_arrow", "[B] <-- [A]\n"),
    ];

    for (name, src) in examples {
        println!("=== Example: {} ===", name);
        println!("Input:\n{}", src.trim());
        println!("---");
        match parser::parse(src) {
            Ok(graph) => println!("{:#?}", graph),
            Err(e) => println!("PARSE ERROR:\n{}", e),
        }
        println!();
    }
}

/// Generate out/phase1/ output files from phase0 syntax examples.
fn gen_phase1_output() {
    fs::create_dir_all("out/phase1").unwrap();

    let examples_txt = fs::read_to_string("out/phase0/syntax_examples.txt")
        .expect("Cannot read out/phase0/syntax_examples.txt");

    // Parse each EXAMPLE N block from the file.
    let examples = extract_examples(&examples_txt);

    let mut ast_out = String::new();
    let mut err_out = String::new();

    // Also test intentionally malformed inputs for parse_errors.txt
    let bad_inputs: &[(&str, &str)] = &[
        ("missing_closing_bracket", "[A --> [B]\n"),
        ("empty_edge_target", "[A] -->\n"),
        ("bad_direction", "direction: DIAG\n[A] --> [B]\n"),
        ("unclosed_subgraph", "subgraph \"Foo\" {\n  [A]\n"),
        ("unknown_token", "@ invalid @\n"),
    ];

    ast_out.push_str("# Phase 1: AST Dump\n");
    ast_out.push_str("# Generated by: cargo run -- --gen-phase1\n");
    ast_out.push_str("# Each example parsed from out/phase0/syntax_examples.txt\n\n");

    err_out.push_str("# Phase 1: Parse Error Examples\n");
    err_out.push_str("# Generated by: cargo run -- --gen-phase1\n\n");

    for (title, src) in &examples {
        ast_out.push_str(&format!("{}\n", "=".repeat(80)));
        ast_out.push_str(&format!("{}\n", title));
        ast_out.push_str(&format!("{}\n", "=".repeat(80)));
        ast_out.push_str("\nInput:\n");
        ast_out.push_str(src.trim());
        ast_out.push_str("\n\nParsed AST:\n");
        match parser::parse(src) {
            Ok(graph) => {
                ast_out.push_str(&format!("{:#?}", graph));
            }
            Err(e) => {
                ast_out.push_str(&format!("PARSE ERROR:\n{}", e));
            }
        }
        ast_out.push_str("\n\n");
    }

    for (label, src) in bad_inputs {
        err_out.push_str(&format!("{}\n", "=".repeat(80)));
        err_out.push_str(&format!("Bad input: {}\n", label));
        err_out.push_str(&format!("{}\n", "=".repeat(80)));
        err_out.push_str("\nInput:\n");
        err_out.push_str(src.trim());
        err_out.push_str("\n\nError:\n");
        match parser::parse(src) {
            Ok(graph) => {
                err_out.push_str(&format!("(parsed successfully — expected error)\n{:#?}", graph));
            }
            Err(e) => {
                err_out.push_str(&e);
            }
        }
        err_out.push_str("\n\n");
    }

    let ast_path = "out/phase1/ast_dump.txt";
    let err_path = "out/phase1/parse_errors.txt";

    fs::write(ast_path, &ast_out).expect("Cannot write ast_dump.txt");
    fs::write(err_path, &err_out).expect("Cannot write parse_errors.txt");

    println!("Generated {}", ast_path);
    println!("Generated {}", err_path);
}

/// Extract (title, body) pairs from the syntax_examples.txt format.
fn extract_examples(text: &str) -> Vec<(String, String)> {
    let mut results = Vec::new();
    let separator = "=".repeat(80);
    let mut lines = text.lines().peekable();
    let mut current_title: Option<String> = None;
    let mut current_body = String::new();
    let mut in_body = false;

    while let Some(line) = lines.next() {
        if line == separator {
            // Next line is the title, then another separator
            if let Some(title_line) = lines.next() {
                let _sep2 = lines.next(); // consume closing separator
                // Save previous example if any
                if let Some(title) = current_title.take() {
                    let trimmed = current_body.trim().to_string();
                    if !trimmed.is_empty() {
                        results.push((title, format!("{}\n", trimmed)));
                    }
                }
                current_title = Some(title_line.trim().to_string());
                current_body.clear();
                in_body = true;
            }
        } else if in_body {
            current_body.push_str(line);
            current_body.push('\n');
        }
    }

    // Push last example
    if let Some(title) = current_title {
        let trimmed = current_body.trim().to_string();
        if !trimmed.is_empty() {
            results.push((title, format!("{}\n", trimmed)));
        }
    }

    results
}

/// Generate out/phase2/ output files: graph topology info and adjacency lists.
fn gen_phase2_output() {
    fs::create_dir_all("out/phase2").unwrap();

    let examples_txt = fs::read_to_string("out/phase0/syntax_examples.txt")
        .expect("Cannot read out/phase0/syntax_examples.txt");
    let examples = extract_examples(&examples_txt);

    let mut info_out = String::new();
    let mut adj_out = String::new();

    info_out.push_str("# Phase 2: Graph Info\n");
    info_out.push_str("# Generated by: cargo run -- --gen-phase2\n");
    info_out.push_str("# Shows topology metrics for each example\n\n");

    adj_out.push_str("# Phase 2: Adjacency Lists\n");
    adj_out.push_str("# Generated by: cargo run -- --gen-phase2\n");
    adj_out.push_str("# Shows outgoing neighbors for each node\n\n");

    for (title, src) in &examples {
        let sep = "=".repeat(80);
        info_out.push_str(&format!("{}\n{}\n{}\n\n", sep, title, sep));
        adj_out.push_str(&format!("{}\n{}\n{}\n\n", sep, title, sep));

        match parser::parse(src) {
            Err(e) => {
                info_out.push_str(&format!("PARSE ERROR: {}\n\n", e));
                adj_out.push_str(&format!("PARSE ERROR: {}\n\n", e));
            }
            Ok(ast_graph) => {
                let gir = graph::GraphIR::from_ast(&ast_graph);

                // Topological order (if DAG).
                let topo_str = match gir.topological_order() {
                    Some(order) => order.join(", "),
                    None => "(cyclic — no topological order)".to_string(),
                };

                info_out.push_str(&format!("Direction:        {:?}\n", gir.direction));
                info_out.push_str(&format!("Node count:       {}\n", gir.node_count()));
                info_out.push_str(&format!("Edge count:       {}\n", gir.edge_count()));
                info_out.push_str(&format!("Is DAG:           {}\n", gir.is_dag()));
                info_out.push_str(&format!("Topological order: {}\n", topo_str));
                info_out.push_str("\nPer-node degrees:\n");
                let mut node_ids: Vec<String> = gir.node_index.keys().cloned().collect();
                node_ids.sort();
                for id in &node_ids {
                    info_out.push_str(&format!(
                        "  {:30} in={} out={}\n",
                        id,
                        gir.in_degree(id),
                        gir.out_degree(id)
                    ));
                }
                if !gir.subgraph_members.is_empty() {
                    info_out.push_str("\nSubgraph members:\n");
                    for (sg_name, members) in &gir.subgraph_members {
                        info_out.push_str(&format!("  [{}]: {}\n", sg_name, members.join(", ")));
                    }
                }
                info_out.push_str("\n");

                // Adjacency list.
                for (id, neighbors) in gir.adjacency_list() {
                    if neighbors.is_empty() {
                        adj_out.push_str(&format!("  {} → (none)\n", id));
                    } else {
                        adj_out.push_str(&format!("  {} → {}\n", id, neighbors.join(", ")));
                    }
                }
                adj_out.push_str("\n");
            }
        }
    }

    let info_path = "out/phase2/graph_info.txt";
    let adj_path = "out/phase2/adjacency.txt";

    fs::write(info_path, &info_out).expect("Cannot write graph_info.txt");
    fs::write(adj_path, &adj_out).expect("Cannot write adjacency.txt");

    println!("Generated {}", info_path);
    println!("Generated {}", adj_path);
}

/// Generate out/phase3/ output files: layer assignment and dummy node insertion for each example.
fn gen_phase3_output() {
    fs::create_dir_all("out/phase3").unwrap();

    let examples_txt = fs::read_to_string("out/phase0/syntax_examples.txt")
        .expect("Cannot read out/phase0/syntax_examples.txt");
    let examples = extract_examples(&examples_txt);

    let mut layer_out = String::new();
    let mut dummy_out = String::new();

    layer_out.push_str("# Phase 3: Layer Assignment\n");
    layer_out.push_str("# Generated by: cargo run -- --gen-phase3\n");
    layer_out.push_str("# Shows which layer (rank) each node is assigned to\n");
    layer_out.push_str("# Algorithm: fixed-point iteration (rank[v] = max(rank[v], rank[u]+1) for each edge u→v)\n\n");

    dummy_out.push_str("# Phase 3: Dummy Node Insertion\n");
    dummy_out.push_str("# Generated by: cargo run -- --gen-phase3\n");
    dummy_out.push_str("# Shows dummy nodes inserted for edges spanning multiple layers\n");
    dummy_out.push_str("# Dummy nodes ensure every edge connects nodes in adjacent layers\n\n");

    for (title, src) in &examples {
        let sep = "=".repeat(80);
        layer_out.push_str(&format!("{}\n{}\n{}\n\n", sep, title, sep));
        dummy_out.push_str(&format!("{}\n{}\n{}\n\n", sep, title, sep));

        match parser::parse(src) {
            Err(e) => {
                layer_out.push_str(&format!("PARSE ERROR: {}\n\n", e));
                dummy_out.push_str(&format!("PARSE ERROR: {}\n\n", e));
            }
            Ok(ast_graph) => {
                let gir = graph::GraphIR::from_ast(&ast_graph);
                let la = layout::LayerAssignment::assign(&gir);
                layer_out.push_str(&la.format_report(&gir));
                layer_out.push('\n');

                // Run dummy node insertion on the cycle-free DAG.
                let (dag, _) = layout::remove_cycles(&gir.digraph);
                let aug = layout::insert_dummy_nodes(&dag, &la);

                dummy_out.push_str(&format!(
                    "Original nodes: {}  |  After insertion: {}  |  Dummy nodes: {}\n",
                    gir.node_count(),
                    aug.graph.node_count(),
                    aug.graph.node_count() - gir.node_count()
                ));
                dummy_out.push_str(&format!(
                    "Long edges broken up: {}\n",
                    aug.dummy_edges.len()
                ));

                if aug.dummy_edges.is_empty() {
                    dummy_out.push_str("  (no long edges — all edges are already adjacent-layer)\n");
                } else {
                    for de in &aug.dummy_edges {
                        dummy_out.push_str(&format!(
                            "  {} → {} : via [{}]\n",
                            de.original_src,
                            de.original_tgt,
                            de.dummy_ids.join(", ")
                        ));
                        for dummy_id in &de.dummy_ids {
                            dummy_out.push_str(&format!(
                                "    {} (layer {})\n",
                                dummy_id,
                                aug.layers[dummy_id]
                            ));
                        }
                    }
                }
                dummy_out.push('\n');
            }
        }
    }

    let layer_path = "out/phase3/layer_assignment.txt";
    let dummy_path = "out/phase3/dummy_nodes.txt";

    fs::write(layer_path, &layer_out).expect("Cannot write layer_assignment.txt");
    fs::write(dummy_path, &dummy_out).expect("Cannot write dummy_nodes.txt");

    println!("Generated {}", layer_path);
    println!("Generated {}", dummy_path);
}
